name: Auto Commit and Push

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger    

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing..."
            git add -A
            git commit -m "Auto-commit: $(date)"
          else
            echo "No changes to commit, skipping..."
          fi

      - name: Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://aman-sharma123:${GH_PAT}@github.com/aman-sharma123/OX-Game.git
          git push origin main
